# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 319)
        MainWindow.setStyleSheet("background-color:rgb(12, 4, 4)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(61, 62, 53, 16))
        self.label.setStyleSheet("color:rgb(255,255,255)")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 137, 71, 22))
        self.pushButton.setStyleSheet("color:rgb(255,255,255);\n"
"border:0.5px solid white")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(61, 114, 103, 16))
        self.label_2.setStyleSheet("color:rgb(255,255,255)")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(61, 180, 221, 22))
        self.pushButton_2.setStyleSheet("color:rgb(255,255,255);\n"
"border:1px solid white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setPlaceholderText(" Enter Server IP")
        self.lineEdit_2.setGeometry(QtCore.QRect(61, 137, 137, 22))
        self.lineEdit_2.setStyleSheet("color:rgb(255,255,255);\n"
"border:1px solid white")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setPlaceholderText(" Enter Share Folder Path ")
        self.lineEdit.setGeometry(QtCore.QRect(61, 85, 137, 22))
        self.lineEdit.setStyleSheet("color:rgb(255,255,255);\n"
"border:1px solid white")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basic Details"))
        self.label.setText(_translate("MainWindow", "Server IP"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "Share Folder Path"))
        self.pushButton_2.setText(_translate("MainWindow", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
